import styles from "../styles/Home.module.css"

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by"></meta>
                <link rel="icon" href="../public/favicon.ico" />
            </Head>
            Hi!
        </div>
    )
}